all: run

run:
	# clear; deno run --allow-net --allow-read --allow-write ./src/main.ts "http://localhost:8000/"
	clear; deno run --allow-net --allow-read --allow-write --unstable ./src/main.ts "http://google.com"

clean:
	rm -R ./requests/requests-*.txt