listOfTags:
	clear; deno run --allow-net get_list_of_tags.ts

listOfArticles:
	clear; deno run --allow-net get_list_of_articles.ts

getArticle:
	clear; deno run --allow-net get_single_article.ts

createArticle:
	clear; deno run --allow-net create_article.ts

updateArticle:
	clear; deno run --allow-net update_article.ts

deleteArticle:
	clear; deno run --allow-net delete_article.ts

favoriteArticle:
	clear; deno run --allow-net favorite_article.ts

feedArticles:
	clear; deno run --allow-net feed_articles.ts

commentsFromArticle:
	clear; deno run --allow-net get_comments_from_article.ts

addCommentsToAnArticle:
	clear; deno run --allow-net add_comments_to_an_article.ts

deleteComment:
	clear; deno run --allow-net delete_comment.ts

getProfile:
	clear; deno run --allow-net get_profile.ts

getCurrentUser:
	clear; deno run --allow-net get_current_user.ts

updateUser:
	clear; deno run --allow-net update_user.ts

authSignInLogin:
	clear; deno run --allow-net auth_sign_in_login.ts

authSignUpRegistration:
	clear; deno run --allow-net auth_sign_up_registration.ts